contigua:	
	gcc -c lista_contigua.c -o lista_contigua.o
	gcc main.c lista_contigua.o -o main
	./main
	
encadeada:
	gcc -c lista_encadeada.c -o lista_encadeada.o
	gcc main.c lista_encadeada.o -o main
	./main

clean:
	rm *.o
	rm main
