contigua:	
	gcc -c fila_contigua.c -o fila_contigua.o
	gcc main.c fila_contigua.o -o main
	./main
	
encadeada:
	gcc -c fila_encadeada.c -o fila_encadeada.o
	gcc main.c fila_encadeada.o -o main
	./main

clean:
	rm *.o
	rm main
