contigua:	
	# Compilando a implementacao da fila
	gcc -c ./libs/pilha_contigua.c -o ./libs/pilha_contigua.o
	
	# Compilando e gerando o executavel
	gcc main.c ./libs/pilha_contigua.o -o main
	
	# Executando
	./main

	
encadeada:
	# Compilando a implementacao da fila
	gcc -c ./libs/pilha_encadeada.c -o ./libs/pilha_encadeada.o
	
	# Compilando e gerando o executavel
	gcc main.c ./libs/pilha_encadeada.o -o main
	
	# Executando
	./main

clean:
	rm *.o
	rm main